import {Capacitor,CapacitorHttp,SystemBars,SystemBarsStyle} from '@capacitor/core';
import {Filesystem,Directory,Encoding} from '@capacitor/filesystem';
import {Preferences} from '@capacitor/preferences';
import {Browser} from '@capacitor/browser';
import {FEEDS,refreshFeeds} from './feed.mjs';
import {CATEGORIES,filterNews,filterCerts} from './discovery.mjs';
import {toggle,move,complete,decodeRoute} from './roadmap.mjs';
import {openArticle} from './article.mjs';
import {saveRoadmap} from './persistence.mjs';
const $=id=>document.getElementById(id),seed=window.__NEWS__||{sources:[],articles:[]};
const certs=(window.__CERTIFICATIONS__||[]).map((row,index)=>({...row,id:`cert-${index}`})),byId=new Map(certs.map(c=>[c.id,c]));
const domains={redops:'Offensive security',blueops:'Defensive security',engineer:'Security engineering',network:'Network security',software:'Application security',iam:'Identity and access',mgmt:'Governance',test:'Audit and testing',asset:'Asset and privacy'};
let news=seed,roadmap={ids:[],done:[]},current='news',shown=45,busy=false,sheetOpener=null,newsFilter={source:'all',categories:[],query:''},certDomain='all';
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=String(text);return node};
const date=value=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString():'Unknown';
const level=value=>Number(value)>=19?'Beginner':Number(value)>=10?'Intermediate':'Advanced';
const note=(id,message)=>$(id).textContent=message;
function external(url,label){const a=el('a','',label);try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))throw Error();a.href=u.href;a.rel='noopener noreferrer';a.target='_blank';if(Capacitor.isNativePlatform())a.onclick=e=>{e.preventDefault();Browser.open({url:u.href}).catch(()=>{})}}catch{a.textContent='Link unavailable'}return a}
function show(name){if(current===name)return;current=name;for(const key of ['news','certs','route']){$(key+'-view').hidden=key!==name;$("tab-"+key).setAttribute('aria-current',key===name?'page':'false')}window.scrollTo(0,0);if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)$(name+'-view').animate([{opacity:.78,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:145,easing:'cubic-bezier(.22,1,.36,1)'})}
let sheetExit=null;
function finishSheetClose(){if($('sheet-backdrop').hidden)return;$('sheet-backdrop').hidden=true;document.body.classList.remove('sheet-open');$('sheet-body').replaceChildren();$('sheet-actions').replaceChildren();sheetOpener?.focus();sheetOpener=null}
function closeSheet(){if($('sheet-backdrop').hidden||sheetExit)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){finishSheetClose();return}sheetExit=$('sheet').animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(16px)'}],{duration:155,easing:'ease-in'});sheetExit.onfinish=()=>{sheetExit=null;finishSheetClose()};sheetExit.oncancel=()=>{sheetExit=null}}
function openSheet(title,body,actions=[]){if(sheetExit){sheetExit.cancel();sheetExit=null}sheetOpener=document.activeElement;$('sheet-title').textContent=title;$('sheet-body').replaceChildren(body);$('sheet-actions').replaceChildren(...actions);$('sheet-backdrop').hidden=false;document.body.classList.add('sheet-open');$('sheet-close').focus()}
$('sheet-close').onclick=closeSheet;$('sheet-backdrop').onclick=e=>{if(e.target===$('sheet-backdrop'))closeSheet()};document.addEventListener('keydown',e=>{if($('sheet-backdrop').hidden)return;if(e.key==='Escape'){closeSheet();return}if(e.key==='Tab'){const nodes=[...$('sheet').querySelectorAll('button:not([disabled]),a[href],input:not([disabled])')];if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function action(text,onClick,cls='quiet'){const button=el('button',cls,text);button.type='button';button.onclick=onClick;return button}
function choice(type,name,value,label,checked){const line=el('label','choice'),input=el('input');input.type=type;input.name=name;input.value=value;input.checked=checked;line.append(input,el('span','',label));return {line,input}}
function openNewsFilters(){let source=newsFilter.source,selected=new Set(newsFilter.categories),body=el('div');body.append(el('h3','','News sources'));for(const option of [{id:'all',name:'All sources'},...(news.sources||[])]){const {line,input}=choice('radio','news-source',option.id,option.name,source===option.id);input.onchange=()=>source=option.id;body.append(line)}body.append(el('h3','','Categories'));for(const [key,label] of CATEGORIES){const {line,input}=choice('checkbox','news-category',key,label,selected.has(key));input.onchange=()=>input.checked?selected.add(key):selected.delete(key);body.append(line)}openSheet('Filter news',body,[action('Clear',()=>{newsFilter={...newsFilter,source:'all',categories:[]};drawNews();closeSheet()}),action('Show stories',()=>{newsFilter={...newsFilter,source,categories:[...selected]};drawNews();closeSheet()},'primary')])}
function openCertFilters(){let domain=certDomain,body=el('div');for(const key of ['all',...[...new Set(certs.map(c=>c.main_domain).filter(Boolean))].sort()]){const {line,input}=choice('radio','cert-domain',key,key==='all'?'All career areas':domains[key]||key,domain===key);input.onchange=()=>domain=key;body.append(line)}openSheet('Career area',body,[action('All areas',()=>{certDomain='all';shown=45;drawCerts();closeSheet()}),action('Apply',()=>{certDomain=domain;shown=45;drawCerts();closeSheet()},'primary')])}
async function readStory(row){const result=await openArticle(row.url,{native:Capacitor.isNativePlatform(),openNative:url=>Browser.open({url}),openWeb:url=>{const opened=window.open(url,'_blank');if(opened)opened.opener=null;return opened}});if(!result.ok)note('update-status',result.reason==='invalid-url'?'The source link is unavailable.':'Could not open the source. Try again when connected.')}
function drawNews(){const rows=filterNews(news.articles||[],{...newsFilter,query:$('news-search').value});const f=newsFilter.categories.length+(newsFilter.source==='all'?0:1);$('news-filter').textContent=f?`Filters (${f})`:'Filters';note('news-count',`${rows.length} of ${news.articles?.length||0} stories`);const list=$('stories');list.replaceChildren();if(!rows.length){list.append(el('p','empty','No stories match. Change or clear the filters.'));return}for(const row of rows){const card=el('article','card story'),open=action('',()=>readStory(row),'story-open');open.setAttribute('aria-label',`Read full article from ${row.sourceName||row.source||'source'}: ${row.title||'Untitled'}`);open.append(el('span','source',`${row.sourceName||row.source||'Source'} · ${date(row.published)}`),el('span','story-title',row.title||'Untitled'),el('span','story-preview',row.extract||'Open the source for the full article.'),el('span','read-label','Read full article in app'));card.append(open);list.append(card)}}
async function save(next){const saved=await saveRoadmap(next,data=>Preferences.set({key:'roadmap-v2',value:JSON.stringify(data)}),message=>note('route-status',message));roadmap=saved;drawCerts();drawRoadmap()}
function certCard(row){const card=el('article','card');card.append(el('div','source',`${domains[row.main_domain]||row.main_domain||'Other'} · ${level(row.skill_row)}`),el('h2','',row.full_name||row.acronym),el('p','sub',`${row.acronym||''} · ${row.cost_notes||'Confirm price and training with the issuer.'}`));const buttons=el('div','card-actions');buttons.append(action(roadmap.ids.includes(row.id)?'Remove from roadmap':'Add to roadmap',async()=>{try{await save(toggle(roadmap,row.id))}catch{note('route-status','Could not save roadmap. Try again.')}}),action('Details',()=>details(row)),external(row.official_url,'Issuer'));card.append(buttons);return card}
function drawCerts(){const rows=filterCerts(certs,$('cert-search').value,certDomain);$('cert-filter').textContent=certDomain==='all'?'All areas':domains[certDomain]||certDomain;note('cert-count',`${rows.length} of ${certs.length} certifications`);$('certs').replaceChildren(...rows.slice(0,shown).map(certCard));$('more').hidden=shown>=rows.length}
function details(row){const body=el('div'),dl=el('dl');const fields=[['Acronym',row.acronym],['Career area',domains[row.main_domain]||row.main_domain],['Level (roadmap estimate)',level(row.skill_row)],['Course modules',row.modules_count||row.course_modules],['Study time',row.study_hours_est?`${row.study_hours_est} hours`:null],['Exam duration',row.exam_minutes?`${row.exam_minutes} minutes`:null],['Price / training',row.cost_notes||row.listed_cost_usd],['Exam questions',row.exam_questions],['Renewal',row.validity_years?`${row.validity_years} years`:null]];for(const [label,value] of fields){const line=el('div','detail');line.append(el('dt','',label),el('dd','',value||'Not listed in the catalogue'));dl.append(line)}body.append(el('p','',row.full_name||row.acronym),dl,el('p','','Check current course modules, price and requirements with the issuer before enrolling.'));openSheet(row.acronym||'Certification details',body,[external(row.official_url,'Official course or exam page')])}
function drawRoadmap(){const list=$('route');list.replaceChildren();$('count').textContent=roadmap.ids.length;if(!roadmap.ids.length){list.append(el('li','empty','No courses yet. Add one from Certifications.'));return}roadmap.ids.forEach((id,index)=>{const row=byId.get(id);if(!row)return;const li=el('li'),card=action('',()=>details(row),'timeline-card');card.classList.toggle('done',roadmap.done.includes(id));card.setAttribute('aria-label',`Details for ${row.full_name||row.acronym}`);card.append(el('span','step',`Step ${index+1} · ${level(row.skill_row)}`),el('strong','',row.full_name||row.acronym),el('span','sub',`${row.acronym||''} · ${domains[row.main_domain]||row.main_domain||'Other'} · Tap for details`));li.append(card);const tools=el('div','timeline-actions'),done=choice('checkbox','',id,'Completed',roadmap.done.includes(id));done.input.onchange=async()=>{try{await save(complete(roadmap,id))}catch{drawRoadmap();note('route-status','Could not save completion. Try again.')}};tools.append(done.line);for(const [name,step] of [['Up',-1],['Down',1]]){const button=action(name,async()=>{try{await save(move(roadmap,id,step))}catch{note('route-status','Could not save order. Try again.')}});button.disabled=index+step<0||index+step>=roadmap.ids.length;tools.append(button)}tools.append(action('Remove',async()=>{try{await save(toggle(roadmap,id))}catch{note('route-status','Could not remove course. Try again.')}}));li.append(tools);list.append(li)})}
function about(){const body=el('div');body.append(el('p','','Independent cybersecurity intelligence and career planning for aspiring security professionals.'),el('p','','© 2026 J.M. All rights reserved.'));const links=el('div','sheet-links');for(const [url,label] of [['mailto:jyotirmay.mondal@efrei.net','Contact'],['https://github.com/Jy0t1may','GitHub'],['https://www.linkedin.com/in/jyotirmay-mondal','LinkedIn']]){if(url.startsWith('mailto:')){const a=el('a','',label);a.href=url;links.append(a)}else links.append(external(url,label))}body.append(links);openSheet('Security Expedition',body)}
async function loadSaved(){try{const file=await Filesystem.readFile({path:'news.json',directory:Directory.Data,encoding:Encoding.UTF8}),cached=JSON.parse(file.data);if(Array.isArray(cached.articles)&&Array.isArray(cached.sources)&&Date.parse(cached.fetchedAt)>Date.parse(seed.fetchedAt))news=cached}catch{}try{const v2=(await Preferences.get({key:'roadmap-v2'})).value,old=(await Preferences.get({key:'roadmap-v1'})).value;roadmap=decodeRoute(v2,old,new Set(byId.keys()));if(!v2&&old&&roadmap.ids.length)await Preferences.set({key:'roadmap-v2',value:JSON.stringify(roadmap)})}catch{}drawNews();drawCerts();drawRoadmap();note('update-status',`Saved feed: ${date(news.fetchedAt)}. Tap to check for updates.`)}
async function update(){if(busy)return;busy=true;$('refresh').disabled=true;note('update-status','Checking feeds…');try{const result=await refreshFeeds({baseline:news,feeds:FEEDS,request:url=>CapacitorHttp.get({url,responseType:'text',connectTimeout:12000,readTimeout:12000})});await Filesystem.writeFile({path:'news.json',directory:Directory.Data,encoding:Encoding.UTF8,data:JSON.stringify(result.news)});news=result.news;drawNews();note('update-status',`Checked ${result.updated.length} of ${FEEDS.length} feeds at ${date(news.fetchedAt)}.${result.failed.length?' Unavailable: '+result.failed.join(', ')+'. Previous posts are retained.':''}`)}catch(e){note('update-status',`${e.message||'Update failed'} Saved posts are unchanged.`)}finally{busy=false;$('refresh').disabled=false}}
for(const key of ['news','certs','route'])$('tab-'+key).onclick=()=>show(key);$('about').onclick=about;$('refresh').onclick=update;$('news-search').oninput=drawNews;$('news-filter').onclick=openNewsFilters;$('cert-search').oninput=()=>{shown=45;drawCerts()};$('cert-filter').onclick=openCertFilters;$('more').onclick=()=>{shown+=45;drawCerts()};
if(Capacitor.isNativePlatform()){SystemBars.show().catch(()=>{});SystemBars.setStyle({style:SystemBarsStyle.Dark}).catch(()=>{})}loadSaved();
